# Generated by Django 2.2 on 2021-08-17 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('ncontent', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
