# Generated by Django 2.2 on 2021-08-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_db_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_href',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
